FROM python:3.11-bullseye

WORKDIR /app

# Install full build toolchain
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    g++ \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Set C++11 flags for hnswlib
ENV CXXFLAGS="-std=c++11"

# Preinstall Python build tools
RUN pip install --upgrade pip setuptools wheel \
    && pip install "cython<3.0" \
    && pip install --no-build-isolation "pyyaml==6.0.1"

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
