FROM python:3.11-bullseye

WORKDIR /app

# Install toolchain
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    g++ \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Inject compiler flags
ENV CXX="g++"
ENV CC="gcc"
ENV CFLAGS="-O2"
ENV CXXFLAGS="-O2 -std=c++11"
ENV LDFLAGS="-lm"

# Install core Python packages
RUN pip install --upgrade pip setuptools wheel \
    && pip install "cython<3.0" \
    && pip install --no-build-isolation "pyyaml==6.0.1"

# Inject remaining dependencies (excluding hnswlib)
COPY requirements.txt .
RUN pip install -r requirements.txt

# Inject precompiled hnswlib binary and metadata
COPY wheels/hnswlib/hnswlib.cpython-311-x86_64-linux-gnu.so /usr/local/lib/python3.11/site-packages/hnswlib/
COPY wheels/hnswlib/hnswlib-0.8.0.dist-info /usr/local/lib/python3.11/site-packages/hnswlib-0.8.0.dist-info/

# Copy your app code
COPY . .

# Boot cockpit HUD
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
