# Dockerfile
FROM python:3.11-slim

WORKDIR /app

# Install build tools for hnswlib
RUN apt-get update && apt-get install -y \
    build-essential \
    g++ \
    cmake \
    && rm -rf /var/lib/apt/lists/*

# Preinstall Python build tools
RUN pip install --upgrade pip setuptools wheel \
    && pip install "cython<3.0" \
    && pip install --no-build-isolation "pyyaml==6.0.1"

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
